### ISSUE TITLE
How can we use this library ?

### ISSUE THREAD

**Issue by dassio** [storj/uplink-c#1]

**Comment by egonelbre** [comment]
Currently this is still a work in progress. We will add more documentation at a later date.

If you wish to experiment, you can do so, by compiling the shared library using `go build -buildmode c-shared storj.io/uplink-c` and then use it to connect to [storj-sim](https://github.com/storj/storj/wiki/Test-network).

**Comment by egonelbre** [comment]
The bindings should be now quite stable.
