### ISSUE TITLE
Make new uplink-c release

### ISSUE THREAD

**Issue by mniewrzal** [storj/uplink-c#23]
Follow https://github.com/storj/uplink-c/blob/main/MAINTAINERS.md to make new release. We should make version **1.8.0** but we should  also first finish `Add new edge.Config field InsecureSkipVerify to bindings` https://github.com/storj/uplink-c/issues/22.

**Comment by Qweder93** [comment]
https://review.dev.storj.io/c/storj/uplink-c/+/9129

**Comment by iglesiasbrandon** [comment]
Waiting for Eriks PR to be pushed.

**Comment by TopperDEL** [comment]
May I come back to this? Can we create a new release with a new tag?

**Comment by mniewrzal** [comment]
This finally done.
