### ISSUE TITLE
Make "register Access in Edge services" work against the production environments

### ISSUE THREAD

**Issue by awcchungster** [storj/uplink-c#8]
This is a feature request.

As a user of the uplink-c library and Python binding, I would like to be able to create a grant that also includes the Storj S3 endpoint available. In the Uplink Python SDK .share function, an optional field can be added share(permissions, prefix, S3). The S3 flag boolean set to `true` would be the equivalent to passing the `--register` flag in the Storj CLI.

Without this feature, I would need to have my code call into bash to run the Storj CLI directly and issue tokens. From there I would need to parse the response back in my code. Lots of room for error in the code and extra work.

**Comment by mniewrzal** [comment]
Hi @awcchungster 
Such functionality already exists in uplink-c bindings under method `edge_register_access`. Unfortunately, this method still doesn't work against the production environments and we are working to solve this problem. When that will happen we will release new version of uplink-c and then python bindings can be updated for this feature as well. We are pretty close to finalize this.

Code: https://github.com/storj/uplink-c/blob/main/edge_access.go#L20
Example: https://github.com/storj/uplink-c/blob/main/testsuite/edge/access_test.c#L33

**Comment by Erikvv** [comment]
All fixed thanks everyone.
